#!/usr/bin/env bash
set -euo pipefail

SERVICE_USER="switchyard"
SERVICE_GROUP="switchyard"
APP_DIR="/opt/switchyard/api"
APP_DLL="${APP_DIR}/SwitchYard.Service.dll"
LOG_DIR="${APP_DIR}/logs"
DATA_DIR="/opt/switchyard/data"
CONF_DIR="/etc/switchyard"
ENV_FILE="${CONF_DIR}/api.env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_UNIT_SRC="${SCRIPT_DIR}/switchyard-api.service"
SYSTEMD_UNIT_DST="/etc/systemd/system/switchyard-api.service"

require_root() {
    if [[ "$(id -u)" -ne 0 ]]; then
        echo "ERROR: run this script with sudo or as root." >&2
        exit 1
    fi
}

ensure_user() {
    if ! id -u "${SERVICE_USER}" >/dev/null 2>&1; then
        echo "[+] Creating system user ${SERVICE_USER}"
        adduser --system --group --no-create-home --shell /usr/sbin/nologin "${SERVICE_USER}"
    else
        echo "[=] System user ${SERVICE_USER} already exists"
    fi
}

ensure_conf_dir() {
    install -d -o root -g "${SERVICE_GROUP}" -m 0750 "${CONF_DIR}"
}

ensure_runtime_dirs() {
    install -d -o "${SERVICE_USER}" -g "${SERVICE_GROUP}" -m 0750 "${LOG_DIR}"
    install -d -o "${SERVICE_USER}" -g "${SERVICE_GROUP}" -m 0750 "${DATA_DIR}"
}

validate_publish_layout() {
    if [[ ! -f "${APP_DLL}" ]]; then
        echo "ERROR: ${APP_DLL} was not found." >&2
        echo "Deploy the published output to ${APP_DIR} before running this script." >&2
        exit 1
    fi

    if [[ ! -f "${SYSTEMD_UNIT_SRC}" ]]; then
        echo "ERROR: ${SYSTEMD_UNIT_SRC} was not found." >&2
        echo "Make sure the publish bundle includes scripts/deploy/." >&2
        exit 1
    fi
}

prompt_secret() {
    local var_name="$1"
    local label="$2"
    local value=""

    while [[ -z "${value}" ]]; do
        read -r -s -p "${label}: " value || true
        echo
        if [[ -z "${value}" ]]; then
            echo "  Value cannot be empty."
        fi
    done

    printf -v "${var_name}" '%s' "${value}"
}

prompt_plain() {
    local var_name="$1"
    local label="$2"
    local default_val="${3:-}"
    local value=""

    while [[ -z "${value}" ]]; do
        if [[ -n "${default_val}" ]]; then
            read -r -p "${label} [${default_val}]: " value || true
            value="${value:-${default_val}}"
        else
            read -r -p "${label}: " value || true
        fi

        if [[ -z "${value}" ]]; then
            echo "  Value cannot be empty."
        fi
    done

    printf -v "${var_name}" '%s' "${value}"
}

backup_if_exists() {
    local path="$1"

    if [[ -f "${path}" ]]; then
        local ts
        ts="$(date +%Y%m%d-%H%M%S)"
        cp -p "${path}" "${path}.bak.${ts}"
        chmod 0600 "${path}.bak.${ts}" || true
        echo "[+] Backed up ${path} to ${path}.bak.${ts}"
    fi
}

write_env_file() {
    local bind_url="$1"
    local db_host="$2"
    local db_port="$3"
    local db_name="$4"
    local db_user="$5"
    local db_pwd="$6"
    local jwt_secret="$7"

    backup_if_exists "${ENV_FILE}"

    local tmp
    tmp="$(mktemp)"
    chmod 0600 "${tmp}"

    cat > "${tmp}" <<EOF
# Generated by install-secrets.sh on $(date -Iseconds)
# Keep this file private. Recommended mode: 0600.
ASPNETCORE_ENVIRONMENT=Production

# Explicitly override the host array so Production does not inherit dev-only listeners.
WebApi__Hosts__0=${bind_url}
WebApi__Hosts__1=

HumpDatabase__DatabaseType=Mysql
HumpDatabase__MysqlConfig__Host=${db_host}
HumpDatabase__MysqlConfig__Port=${db_port}
HumpDatabase__MysqlConfig__Database=${db_name}
HumpDatabase__MysqlConfig__Username=${db_user}
HumpDatabase__MysqlConfig__Password=${db_pwd}
HumpDatabase__MysqlConfig__SslMode=Preferred
HumpDatabase__MysqlConfig__CharSet=utf8mb4
HumpDatabase__MysqlConfig__ConnectionTimeout=15

Jwt__SecretKey=${jwt_secret}
EOF

    install -o "${SERVICE_USER}" -g "${SERVICE_GROUP}" -m 0600 "${tmp}" "${ENV_FILE}"
    rm -f "${tmp}"
    echo "[+] Wrote ${ENV_FILE}"
}

install_unit() {
    install -o root -g root -m 0644 "${SYSTEMD_UNIT_SRC}" "${SYSTEMD_UNIT_DST}"
    systemctl daemon-reload
    echo "[+] Installed ${SYSTEMD_UNIT_DST}"
}

uninstall() {
    require_root

    if [[ -f "${ENV_FILE}" ]]; then
        local ts
        ts="$(date +%Y%m%d-%H%M%S)"
        mv "${ENV_FILE}" "${ENV_FILE}.removed.${ts}"
        chmod 0600 "${ENV_FILE}.removed.${ts}" || true
        echo "[+] Moved ${ENV_FILE} to ${ENV_FILE}.removed.${ts}"
    fi

    if [[ -f "${SYSTEMD_UNIT_DST}" ]]; then
        systemctl disable --now switchyard-api 2>/dev/null || true
        rm -f "${SYSTEMD_UNIT_DST}"
        systemctl daemon-reload
        echo "[+] Removed ${SYSTEMD_UNIT_DST}"
    fi

    echo "[OK] Uninstall finished. Runtime directories were left in place."
}

main() {
    if [[ "${1:-}" == "--uninstall" ]]; then
        uninstall
        exit 0
    fi

    require_root
    validate_publish_layout
    ensure_user
    ensure_conf_dir
    ensure_runtime_dirs

    echo
    echo "===== SwitchYard production secret installer ====="
    echo "Input is hidden for passwords and JWT secrets."
    echo

    local bind_url db_host db_port db_name db_user db_pwd jwt_secret

    prompt_plain  bind_url   "Kestrel bind URL" "http://127.0.0.1:7297"
    prompt_plain  db_host    "MySQL host" "127.0.0.1"
    prompt_plain  db_port    "MySQL port" "3306"
    prompt_plain  db_name    "MySQL database" "hump"
    prompt_plain  db_user    "MySQL username"
    prompt_secret db_pwd     "MySQL password"

    if [[ "${JWT_AUTOGEN:-0}" == "1" ]]; then
        if ! command -v openssl >/dev/null 2>&1; then
            echo "ERROR: openssl is required when JWT_AUTOGEN=1." >&2
            exit 1
        fi
        jwt_secret="$(openssl rand -base64 64 | tr -d '\n')"
        echo "[+] Generated a random JWT signing key"
    else
        prompt_secret jwt_secret "Jwt__SecretKey"
    fi

    write_env_file "${bind_url}" "${db_host}" "${db_port}" "${db_name}" "${db_user}" "${db_pwd}" "${jwt_secret}"
    install_unit

    echo
    echo "===== Done ====="
    echo "Next steps:"
    echo "  1) sudo systemctl enable --now switchyard-api"
    echo "  2) sudo systemctl status switchyard-api"
    echo "  3) sudo journalctl -u switchyard-api -f"
}

main "$@"
